language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=mysql
  - DB=sqlite
  - DB=postgres

matrix:
  allow_failures:
    - php: hhvm
  # hhvm doesn't support postgres currently
  exclude:
    - php: hhvm
      env: DB=postgres

before_script: tests/travis/before.sh

script: phpunit --configuration tests/travis/$DB/phpunit.xml
